### ISSUE TITLE
Creating a Heroku App: Naming Error

### ISSUE THREAD

**Issue by UPstartDeveloper** [MakeSchool-Tutorials/Flask-Playlistr#1]
On page 10, the instructions say to deploy to Heroku using the terminal command below:

$ heroku create Playlister-MY-INITIALS 
$ git remote -v

However when I tried this in my machine, it resulted in the following error message: 
 ▸    Name must start with a letter, end with a letter or digit and can only contain
 ▸    lowercase letters, digits, and dashes.

I believe the instructions above should be changed, so the first command I listed instead says:

$ heroku create playlister-MY-INITIALS

I tried that command instead (replacing with my own initials), and I found it worked okay after that.

**Comment by ibirnam** [comment]
@UPstartDeveloper - great catch! just pushed up a fix for the tutorial, should be live in a couple minutes
