### ISSUE TITLE
6. Edit Route: Editing and Updating a Resource

### ISSUE THREAD

**Issue by SamuelFolledo** [MakeSchool-Tutorials/Flask-Playlistr#3]
In templates/playlists_edit.html 
**There is an extra / in this line** after rows='10'
```<textarea` id='playlist-videos' name='videos' rows='10' />{{ "\n".join(playlist.videos) }}</textarea>```

**Comment by ibirnam** [comment]
Good catch @SamuelFolledo ! fixed in 7a03f7ff852d9c131f4348a3b419f2efd35f3efb, should be live in a few minutes
