### ISSUE TITLE
Issue in page 10 Push to Production with Heroku

### ISSUE THREAD

**Issue by SamuelFolledo** [MakeSchool-Tutorials/Flask-Playlistr#5]
In Adding Procfile
Paste the following into your new Procfile and save:
```(env) $ web: gunicorn app:app```

**Please remove** the ```(env) $ ``` as it is not needed. That line is to paste to the Procfile, and not for the terminal

**Comment by ibirnam** [comment]
@SamuelFolledo - thanks for catching that! Fixed in 7894f839923d084116964bff3c8cf833a7dfda9a and will be live in a few of minutes
