### ISSUE TITLE
12. Adding a Route for Comments

### ISSUE THREAD

**Issue by MackRoe** [MakeSchool-Tutorials/Flask-Playlistr#7]
Additional required imports ( request, redirect, url_for) not mentioned. 
Import statement for this step in the tutorial should be updated to:
`from flask import Flask, render_template, request, redirect, url_for`

**Comment by ibirnam** [comment]
Hey @MackRoe! This import is actually given in Chapter 4 - "Creating a Playlist". I did just push an update to remind folks to make sure they have that import for this chapter!
